### PR TITLE
Fix typo: sarch -> search

### PR DESCRIPTION
**Pull request by karanjthakkar**

### CODE REVIEW

**Comment by kdzwinel** [comment]
Unfortunately, this file is being imported from the [chromium source code](https://cs.chromium.org/search/?q=%22from+the+sarch+with%22&sq=package:chromium&type=cs) so fixing it here is pointless. On the other hand it's a great opportunity to contribute to Chrome 😉

**Comment by karanjthakkar** [comment]
@kdzwinel Thanks for link! Could I trouble you into pointing me to a contribution guide to Chromium? 🙈 I could just find the code but no guide on how to go about sending my patch.

**Comment by paulirish** [comment]
[Chrome DevTools Contribution Guide](https://docs.google.com/document/d/1WNF-KqRSzPLUUfZqQG5AFeU_Ll8TfWYcJasa_XGf7ro/edit)

**Comment by karanjthakkar** [comment]
Done! https://chromium-review.googlesource.com/c/chromium/src/+/646806 🎊 Thanks for the help y'all 💛

**Comment by kdzwinel** [comment]
Congrats!

**Comment by paulirish** [comment]
@karanjthakkar whoaaa. hero. thanks for putting in the time to fix this. :)

**Pull request closed without merging**
