### PR TITLE
Allow extension by adding additional protocol files

### PR DESCRIPTION
**Pull request by pipobscure**

### CODE REVIEW

**Comment by paulirish** [comment]
... but why?

**Comment by pipobscure** [comment]
Sorry for the slow reply, I had to get all my CLA ducks into a row first.

The motivation for this is that we have a proxy that implements CDP and forwards much of the protocol to a number of chromium instances backing it. However it also has a few commands geared toward managing the environment.

Adding this makes it easy to simply specify the additional commands by adding a single untacked file to the repository contents and means we don't actually have to change anything to render the relevant type definitions out. Given that it also doesn't actually make a difference otherwise, I figured this would be something we could upstream.

**Comment by o0101** [comment]
@pipobscure It's a cool idea and while I can't speak for the authors, I think it's unlikely the protocol itself will support protocol extensions like this. This is a central product that is relied on by many teams, not just in Chromium/Google but everywhere. Adding this ability would be a gigantic change (not in terms of code required, but in terms of the concept of what the protocol is), and seems unlikely to happen. 

Conceivably it might also create maintenance burden and confusion with people coming here or on Chromium issues tracker for issues related to protocol extensions. 

Additionally, the way these types of 'extended layers' seem to be handled by the ecosystem is exemplified by things like Puppeteer and Playwright, where a separate DSL/API is built atop the raw protocol, rather than emphasizing hacking on CDP itself. Saying that, tho, I also use the raw CDP and prefer the approach you outline here. In essence, even pptr et al are hacking on the raw protocol. I think eventually something like what you propose may happen, but it just seems, to my experience of observing this ecosystem, unlikely that it will happen here. 

Still, it's really cool what you're doing. 

Maybe I'm reading it wrong, but that's just my take on the likelihood.

**Review by 10208612 — APPROVED** [review]
22$

**Pull request closed without merging**
